### ISSUE TITLE
Wellknown overriding supplied scopes given in config

### ISSUE THREAD

**Issue by DarkKlaw** [jpmanson/EasyOIDC#1]
Just tried EasyOIDC to add OIDC support for a nicegui app I am prototyping.
It was quite easy to get started. I however encountered a weird issue of receiving a bad scope error when I was supplying the right scopes in the config.

After digging, we noticed that this line (https://github.com/jpmanson/EasyOIDC/blob/bbe0d6766b169920402d1d317b1725fe7fb806c0/EasyOIDC/config.py#L114) was overriding the scope given in the config. This is a problem for my context since our keycloak instance has a lot of clients and groups and not all clients require all scopes by design.

As a solution, I suggest using the wellknown to verify the config scopes are correct rather than using them to override the value. However, I could have misunderstood the use of supplying the wellknown endpoint in the config.

**Comment by jpmanson** [comment]
Hi @DarkKlaw !

Thanks for your feedback. 

You're right. The "wellknow" URL gives us the supported scopes, but that does not mean that we should implement all of them in the client. It is correct that the library should not copy that parameter and overwrite the local configuration.

We could do the following:
1) If `self.scope` is not defined, then copy scopes_supported from the server (as currently done).
2) If `self.scope` is defined, validate that each scope value is supported as indicated by the server in scopes_supported. For example, if the client has the scope `"openid,profile,email,roles"` and the server supports `"openid,profile,email"`, then raise an error.

Any suggestions on this?
Bye!

**Comment by jpmanson** [comment]
I've implemented the new behaviour in v0.1.8

**Comment by DarkKlaw** [comment]
> Hi @DarkKlaw !
> 
> Thanks for your feedback.
> 
> You're right. The "wellknow" URL gives us the supported scopes, but that does not mean that we should implement all of them in the client. It is correct that the library should not copy that parameter and overwrite the local configuration.
> 
> We could do the following:
> 
>     1. If `self.scope` is not defined, then copy scopes_supported from the server (as currently done).
> 
>     2. If `self.scope` is defined, validate that each scope value is supported as indicated by the server in scopes_supported. For example, if the client has the scope `"openid,profile,email,roles"` and the server supports `"openid,profile,email"`, then raise an error.
> 
> 
> Any suggestions on this? Bye!

Sorry for the late reply. This was what I was thinking as well.
